### ISSUE TITLE
[help] swiper 라이브러리 사용, ESLint가 process 전역 변수를 인식하지 못함 이슈

### ISSUE THREAD

**Issue by olseul** [555team/rolling#47]
**📝 DESCRIBE**
- hook 사용하려고 했는데 다음 사진과 같은 이유때문인 지 리퀘스트가 안돼서 일단 직접 fetch로 받아왔습니다. 원인을 아시는 분 도움 주시길 바랍니다 ㅜㅜ..
<img width="444" alt="스크린샷 2023-11-10 오전 2 36 49" src="https://github.com/codeit-1st-team5/rolling/assets/72639353/af34470d-75cd-4733-abe4-8dd6f93918c7">

**Comment by kanglocal** [comment]
혹시... 서버 재시작해도 여전히 안될까용...??

**Comment by olseul** [comment]
네에 ㅜㅜ

**Comment by hongjw030** [comment]
아니면 캐러셀 구현할 때 부트스트랩 사용하는 건 어떠신가요???
저는 3주차 반응형 웹 만들기였나 코드잇 인강 보다가 캐러셀을 써봤는데, 부트스트랩 쓰면 그냥 자동으로 슬라이딩 모션이 되더라구요.
(https://www.codeit.kr/topics/responsive-web-publishing/lessons/697)

(부트스트랩 캐러셀)
https://getbootstrap.com/docs/4.0/components/carousel/#with-controls

(부트스트랩 캐러셀 자동 재생 멈추는 법)
https://m.blog.naver.com/websearch/220820536071

**Comment by olseul** [comment]
```
env: {
    node: true,
    commonjs: true,
    browser: true,
    es6: true,
  },

```
process 객체는 Node.js 환경에서만 정의되고 사용되므로, "node": true 설정을 추가함으로써 린터가 Node.js 환경에서 실행되고 있음을 인식하고 process 객체 사용에 문제가 없음을 확인했기 때문에 빨간 줄이 사라졌습니다!
